source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'coffee-script'
gem 'sprockets', github:'rails/sprockets'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'teaspoon-jasmine', github:'jejacks0n/teaspoon'
  gem 'teaspoon-bundle', path: '../../'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
